### ISSUE TITLE
Error Handlers

### ISSUE THREAD

**Issue by samsimsom** [felipeflorencio/StartingWithBlueprintTutorial#1]
Hi,
Thank you so much for this Flask tutorial.

I used this template and I really like it, but I have some issues about implementation custom Error Handlers. Custom 404 or 500 pages.

I created new package in blueprints folder like others.

error_views.py
`from flask import Blueprint, render_template
from extensions.database import db

error = Blueprint('error', __name__,
                  template_folder='templates')

@error.errorhandler(404)
def page_not_found(error):
    return render_template('error/404.html'), 404

@error.errorhandler(500)
def internal_server_error(error):
    db.session.rollback()
    return render_template('error/500.html'), 500`

after that i tryed to register to inside create_app function.
app.register_blueprint(error)

but it doesn't catch any errors.

How can I implement this pages?

**Comment by samsimsom** [comment]
I fixed, my bad :(

[error_handler for blueprints](https://stackoverflow.com/questions/12768825/flask-error-handler-for-blueprints)

**Comment by felipeflorencio** [comment]
No problem man :), I do have plan to write one post only about it, to share some guidelines about it :)
